/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 .\\public\\models\\seaPlane.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { SeaPlane } from "./SeaPlane";

export function TowerScene(props) {
  const { nodes, materials } = useGLTF("./models/seaPlane.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials.tower}
        position={[0.01, 1.39, -2.93]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials.house1}
        position={[0.01, 1.04, -2.05]}
        scale={[0.35, 0.44, 0.35]}
      />
      <mesh geometry={nodes["House-pad"].geometry} material={materials.floor} />
      <group position={[0.01, 0.71, -1.29]} scale={[0.35, 0.44, 0.35]}>
        <mesh geometry={nodes.Cube005_1.geometry} material={materials.roof} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials.bg} />
      </group>
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials.Woodtile}
        position={[0.01, 1.04, -2.05]}
        scale={[0.35, 0.44, 0.35]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials.house1}
        position={[0.01, 0.71, -1.29]}
        scale={[0.35, 0.44, 0.35]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[0.01, 1.04, -2.05]}
        scale={[0.35, 0.44, 0.35]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials.Woodtile}
        position={[-0.21, 1.19, -1.21]}
        scale={[0.21, 0.44, 0.35]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials.Woodtile}
        position={[-0.04, 1.15, -1.23]}
        rotation={[-0.05, 0, 0]}
        scale={[0.21, 0.44, 0.35]}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials.Woodtile}
        position={[0.21, 1.19, -1.22]}
        rotation={[0.01, 0, 0]}
        scale={[0.21, 0.44, 0.35]}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials.Woodtile}
        position={[0.15, 1.07, -1.23]}
        scale={[0.35, 0.44, 0.35]}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={materials.roof}
        position={[0.01, 1.04, -2.05]}
        scale={[0.35, 0.44, 0.35]}
      />
      <mesh
        geometry={nodes.Cube015.geometry}
        material={nodes.Cube015.material}
        position={[0.01, 1.39, -2.93]}
      />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={materials.roof}
        position={[0.01, 3.23, -3.11]}
      />
      <mesh
        geometry={nodes.Cube017.geometry}
        material={nodes.Cube017.material}
        position={[0.01, 3.56, -2.59]}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={materials.Woodtile}
        position={[0.01, 3.23, -3.11]}
      />
      <mesh
        geometry={nodes.Cube019.geometry}
        material={materials["tower-top"]}
        position={[0.01, 4.43, -3.11]}
      />
      <mesh
        geometry={nodes.Cube020.geometry}
        material={materials.roof}
        position={[0.01, 3.99, -3.11]}
        scale={0.94}
      />
      <mesh
        geometry={nodes.Cube021.geometry}
        material={materials.house1}
        position={[0.77, 0.89, -3.1]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.27, 0.34, 0.27]}
      />
      <mesh
        geometry={nodes.Cube024.geometry}
        material={nodes.Cube024.material}
        position={[0.77, 0.89, -3.1]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.27, 0.34, 0.27]}
      />
      <mesh
        geometry={nodes.Cube025.geometry}
        material={materials.roof}
        position={[0.77, 0.89, -3.1]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.27, 0.34, 0.27]}
      />
      <mesh geometry={nodes.Fence.geometry} material={materials.roof} />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials.deck}
        position={[0.42, 0.32, -0.06]}
      />
      <mesh
        geometry={nodes.Plane031.geometry}
        material={materials.deck}
        position={[1.35, 0.07, 2.17]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.79}
      />
      <mesh
        geometry={nodes.Fence001.geometry}
        material={materials["tiles-stone"]}
        position={[2.53, 0.23, -1.01]}
        rotation={[0.01, -0.01, -1.11]}
        scale={0.52}
      />
      <mesh
        geometry={nodes.Fence002.geometry}
        material={materials["tiles-stone"]}
        position={[2.61, 0.1, -1.26]}
        rotation={[0.02, -0.03, -0.98]}
        scale={[0.52, 0.52, 0.39]}
      />
      <mesh
        geometry={nodes.Fence003.geometry}
        material={materials["tiles-stone"]}
        position={[2.51, 0.28, -1.77]}
        rotation={[0.02, -0.03, -0.98]}
        scale={[0.52, 0.52, 0.39]}
      />
      <mesh
        geometry={nodes.Fence004.geometry}
        material={materials["tiles-stone"]}
        position={[1.92, 0.41, -1.14]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.85, 0.29, 0.85]}
      />
      <mesh
        geometry={nodes.Fence005.geometry}
        material={materials["tiles-stone"]}
        position={[2.67, 0.17, -2.4]}
        rotation={[0.08, -0.12, -0.94]}
        scale={0.52}
      />
      <mesh
        geometry={nodes.Fence006.geometry}
        material={materials["tiles-stone"]}
        position={[2.71, 0.25, -3.16]}
        rotation={[0.05, -0.07, -1.07]}
        scale={0.52}
      />
      <mesh
        geometry={nodes.Fence007.geometry}
        material={materials["tiles-stone"]}
        position={[2.82, 0.09, -3.42]}
        rotation={[0.05, -0.07, -1.08]}
        scale={0.52}
      />
      <mesh
        geometry={nodes.Fence008.geometry}
        material={materials["tiles-stone"]}
        position={[1.69, 0.22, -0.55]}
        rotation={[0.91, -1.46, -0.37]}
        scale={0.52}
      />
      <mesh
        geometry={nodes.Fence009.geometry}
        material={materials["tiles-stone"]}
        position={[1.29, 0.06, -0.48]}
        rotation={[1.07, -1.47, -0.09]}
        scale={0.52}
      />
      <mesh
        geometry={nodes.Fence010.geometry}
        material={materials["tiles-stone"]}
        position={[2.16, 0.27, -0.58]}
        rotation={[1.07, -1.47, -0.09]}
        scale={0.46}
      />
      <mesh
        geometry={nodes.Fence011.geometry}
        material={materials["tiles-stone"]}
        position={[1.97, 0.08, -0.5]}
        rotation={[1.07, -1.47, -0.09]}
        scale={0.37}
      />
      <mesh
        geometry={nodes.Fence012.geometry}
        material={materials["tiles-stone"]}
        position={[3.52, 0.18, -3.75]}
        rotation={[1.2, -1.54, 0]}
        scale={0.52}
      />
      <mesh
        geometry={nodes.Fence013.geometry}
        material={materials["tiles-stone"]}
        position={[3.85, 0.3, -3.79]}
        rotation={[1.2, -1.54, 0]}
        scale={0.52}
      />
      <mesh
        geometry={nodes.Fence014.geometry}
        material={materials["tiles-stone"]}
        position={[1.12, 0.41, -1.37]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.89, 0.3, 0.89]}
      />
      <mesh
        geometry={nodes.Fence015.geometry}
        material={materials["tiles-stone"]}
        position={[1, 0.41, -2.68]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.89, 0.3, 0.89]}
      />
      <mesh
        geometry={nodes.Fence016.geometry}
        material={materials["tiles-stone"]}
        position={[0.52, 0.41, -1.4]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.8, 0.28, 0.8]}
      />
      <mesh
        geometry={nodes.Fence017.geometry}
        material={materials["tiles-stone"]}
        position={[1.76, 0.41, -2.06]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.85, 0.29, 0.85]}
      />
      <mesh
        geometry={nodes.Fence018.geometry}
        material={nodes.Fence018.material}
        position={[1.3, 0.41, -3.6]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.69, 0.24, 0.69]}
      />
      <mesh
        geometry={nodes.Fence019.geometry}
        material={materials["tiles-stone"]}
        position={[1.72, 0.41, -1.44]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.89, 0.3, 0.89]}
      />
      <mesh
        geometry={nodes.Fence020.geometry}
        material={materials["tiles-stone"]}
        position={[1.46, 0.41, -1.74]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.89, 0.3, 0.89]}
      />
      <mesh
        geometry={nodes.Fence021.geometry}
        material={materials["tiles-stone"]}
        position={[2.06, 0.41, -1.74]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.89, 0.3, 0.89]}
      />
      <mesh
        geometry={nodes.Fence022.geometry}
        material={materials["tiles-stone"]}
        position={[2.08, 0.41, -2.49]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.85, 0.29, 0.85]}
      />
      <mesh
        geometry={nodes.Fence023.geometry}
        material={materials["tiles-stone"]}
        position={[1.86, 0.41, -2.79]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.85, 0.29, 0.85]}
      />
      <mesh
        geometry={nodes.Fence024.geometry}
        material={materials["tiles-stone"]}
        position={[1.75, 0.41, -3.48]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.65, 0.22, 0.65]}
      />
      <mesh
        geometry={nodes.Fence025.geometry}
        material={materials["tiles-stone"]}
        position={[0.78, 0.41, -1.72]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.71, 0.24, 0.71]}
      />
      <mesh
        geometry={nodes.Fence026.geometry}
        material={materials["tiles-stone"]}
        position={[2.3, 0.41, -3.84]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.72, 0.25, 0.72]}
      />
      <mesh
        geometry={nodes.Fence027.geometry}
        material={materials["tiles-stone"]}
        position={[1.83, 0.41, -3.72]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.65, 0.22, 0.65]}
      />
      <mesh
        geometry={nodes.Fence028.geometry}
        material={materials["tiles-stone"]}
        position={[1.7, 0.41, -3.97]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.65, 0.22, 0.65]}
      />
      <mesh
        geometry={nodes.Fence029.geometry}
        material={materials["tiles-stone"]}
        position={[-1.52, 0.41, -1.14]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.85, 0.29, 0.85]}
      />
      <mesh
        geometry={nodes.Fence030.geometry}
        material={materials["tiles-stone"]}
        position={[-2.31, 0.41, -1.37]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.89, 0.3, 0.89]}
      />
      <mesh
        geometry={nodes.Fence031.geometry}
        material={materials["tiles-stone"]}
        position={[-1.67, 0.41, -2.06]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.85, 0.29, 0.85]}
      />
      <mesh
        geometry={nodes.Fence032.geometry}
        material={materials["tiles-stone"]}
        position={[-1.72, 0.41, -1.44]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.89, 0.3, 0.89]}
      />
      <mesh
        geometry={nodes.Fence033.geometry}
        material={materials["tiles-stone"]}
        position={[-1.98, 0.41, -1.74]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.89, 0.3, 0.89]}
      />
      <mesh
        geometry={nodes.Fence034.geometry}
        material={materials["tiles-stone"]}
        position={[-1.38, 0.41, -1.74]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.89, 0.3, 0.89]}
      />
      <mesh
        geometry={nodes.Fence035.geometry}
        material={materials["tiles-stone"]}
        position={[-0.56, 0.41, -2.34]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.89, 0.3, 0.89]}
      />
      <mesh
        geometry={nodes.Fence036.geometry}
        material={materials["tiles-stone"]}
        position={[-0.42, 0.41, -1.25]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.72, 0.25, 0.72]}
      />
      <mesh
        geometry={nodes.Fence037.geometry}
        material={materials["tiles-stone"]}
        position={[-2.97, 0.41, -2.28]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.85, 0.29, 0.85]}
      />
      <mesh
        geometry={nodes.Fence038.geometry}
        material={materials["tiles-stone"]}
        position={[-2.13, 0.41, -3.28]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.89, 0.3, 0.89]}
      />
      <mesh
        geometry={nodes.Fence039.geometry}
        material={materials["tiles-stone"]}
        position={[-3.12, 0.41, -3.21]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.85, 0.29, 0.85]}
      />
      <mesh
        geometry={nodes.Fence040.geometry}
        material={materials["tiles-stone"]}
        position={[-3.16, 0.41, -2.58]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.89, 0.3, 0.89]}
      />
      <mesh
        geometry={nodes.Fence041.geometry}
        material={materials["tiles-stone"]}
        position={[-3.42, 0.41, -2.89]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.89, 0.3, 0.89]}
      />
      <mesh
        geometry={nodes.Fence042.geometry}
        material={materials["tiles-stone"]}
        position={[-2.83, 0.41, -2.89]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.89, 0.3, 0.89]}
      />
      <mesh
        geometry={nodes.Fence043.geometry}
        material={materials["tiles-stone"]}
        position={[-2.8, 0.41, -3.64]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.85, 0.29, 0.85]}
      />
      <mesh
        geometry={nodes.Fence044.geometry}
        material={materials["tiles-stone"]}
        position={[-3.02, 0.41, -3.94]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.85, 0.29, 0.85]}
      />
      <mesh
        geometry={nodes.Fence045.geometry}
        material={materials["tiles-stone"]}
        position={[-0.56, 0.41, -3.89]}
        rotation={[Math.PI, -1.56, Math.PI]}
        scale={[0.89, 0.3, 0.89]}
      />
      <mesh
        geometry={nodes.Cube_Cube002.geometry}
        material={nodes.Cube_Cube002.material}
        position={[-4.36, -0.09, -2.18]}
        rotation={[Math.PI / 2, 0, -2.68]}
        scale={[1.24, 1.24, 1]}
      />
      <mesh
        geometry={nodes.Cube_Cube001.geometry}
        material={materials["Material.004"]}
        position={[-3.64, -0.34, -0.42]}
        rotation={[Math.PI / 2, 0, -2.68]}
        scale={[1.28, 1.28, 1.03]}
      />
      <mesh
        geometry={nodes.Cube_Cube003.geometry}
        material={materials["Material.004"]}
        position={[4.06, -0.55, -1.73]}
        rotation={[Math.PI / 2, 0, -2.68]}
        scale={[1.83, 1.83, 1.47]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials.roof}
        position={[0.46, 0.78, -1.52]}
        rotation={[0, 0, -0.51]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={materials.house1}
        position={[0.46, 0.66, -1.87]}
        scale={[0.12, 0.12, 0.38]}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={nodes.Plane003.material}
        position={[-0.23, 2.8, -2.51]}
        rotation={[1.52, 0, 0]}
        scale={[0.28, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane004.geometry}
        material={nodes.Plane004.material}
        position={[0.26, 2.71, -2.5]}
        rotation={[1.52, 0, 0]}
        scale={[0.28, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane005.geometry}
        material={nodes.Plane005.material}
        position={[0.26, 2.11, -2.47]}
        rotation={[1.52, 0, 0]}
        scale={[0.28, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane006.geometry}
        material={nodes.Plane006.material}
        position={[-0.29, 2.03, -2.47]}
        rotation={[1.52, 0, 0]}
        scale={[0.28, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={nodes.Plane007.material}
        position={[-0.16, 2.2, -2.48]}
        rotation={[1.52, 0, 0]}
        scale={[0.23, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane008.geometry}
        material={nodes.Plane008.material}
        position={[0.66, 2.66, -2.91]}
        rotation={[1.57, 0.05, -1.57]}
        scale={[0.28, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane009.geometry}
        material={nodes.Plane009.material}
        position={[0.67, 2.55, -3.36]}
        rotation={[1.57, 0.05, -1.57]}
        scale={[0.28, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane010.geometry}
        material={nodes.Plane010.material}
        position={[0.67, 2.46, -3.23]}
        rotation={[1.57, 0.05, -1.57]}
        scale={[0.28, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane011.geometry}
        material={nodes.Plane011.material}
        position={[0.7, 1.98, -2.91]}
        rotation={[1.57, 0.05, -1.57]}
        scale={[0.28, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane012.geometry}
        material={nodes.Plane012.material}
        position={[0.7, 1.89, -3.32]}
        rotation={[1.57, 0.05, -1.57]}
        scale={[0.28, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane013.geometry}
        material={nodes.Plane013.material}
        position={[0.71, 1.78, -3.09]}
        rotation={[1.57, 0.05, -1.57]}
        scale={[0.23, 0.05, 0.03]}
      />
      <mesh
        geometry={nodes.Plane014.geometry}
        material={nodes.Plane014.material}
        position={[0.72, 1.57, -2.76]}
        rotation={[1.57, 0.05, -1.57]}
        scale={[0.28, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane015.geometry}
        material={nodes.Plane015.material}
        position={[0.73, 1.34, -3.38]}
        rotation={[1.57, 0.05, -1.57]}
        scale={[0.28, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane016.geometry}
        material={nodes.Plane016.material}
        position={[0.73, 1.24, -3.37]}
        rotation={[1.57, 0.05, -1.57]}
        scale={[0.23, 0.05, 0.03]}
      />
      <mesh
        geometry={nodes.Plane017.geometry}
        material={nodes.Plane017.material}
        position={[-0.23, 4.22, -2.58]}
        rotation={[1.52, 0, 0]}
        scale={[0.25, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane018.geometry}
        material={nodes.Plane018.material}
        position={[-0.1, 4.3, -2.58]}
        rotation={[1.52, 0, 0]}
        scale={[0.22, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane019.geometry}
        material={nodes.Plane019.material}
        position={[0.31, 4.15, -2.58]}
        rotation={[1.52, 0, 0]}
        scale={[0.18, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane020.geometry}
        material={nodes.Plane020.material}
        position={[-0.02, 4.02, -2.57]}
        rotation={[1.52, 0, 0]}
        scale={[0.19, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane021.geometry}
        material={nodes.Plane021.material}
        position={[0.65, 2.88, -3.08]}
        rotation={[1.57, 0.05, -1.57]}
        scale={[0.23, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane022.geometry}
        material={nodes.Plane022.material}
        position={[0.59, 4.11, -2.94]}
        rotation={[1.57, 0.05, -1.57]}
        scale={[0.28, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane023.geometry}
        material={nodes.Plane023.material}
        position={[0.6, 4.01, -3.38]}
        rotation={[1.57, 0.05, -1.57]}
        scale={[0.22, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane024.geometry}
        material={nodes.Plane024.material}
        position={[0.6, 3.92, -3.01]}
        rotation={[1.57, 0.05, -1.57]}
        scale={[0.22, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane025.geometry}
        material={nodes.Plane025.material}
        position={[0.59, 4.23, -3.3]}
        rotation={[1.57, 0.05, -1.57]}
        scale={[0.16, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane026.geometry}
        material={nodes.Plane026.material}
        position={[0.58, 4.34, -2.95]}
        rotation={[1.57, 0.05, -1.57]}
        scale={[0.22, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane027.geometry}
        material={nodes.Plane027.material}
        position={[0.61, 3.74, -2.79]}
        rotation={[1.57, 0.05, -1.57]}
        scale={[0.12, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Plane028.geometry}
        material={nodes.Plane028.material}
        position={[0.62, 3.62, -3.14]}
        rotation={[1.57, 0.05, -1.57]}
        scale={[0.28, 0.08, 0.03]}
      />
      <mesh
        geometry={nodes.Icosphere.geometry}
        material={nodes.Icosphere.material}
        position={[-5.18, -0.09, -2.2]}
        scale={[0.24, 0.16, 0.24]}
      />
      <mesh
        geometry={nodes.Icosphere002.geometry}
        material={nodes.Icosphere002.material}
        position={[-5.28, -0.12, -1.95]}
        rotation={[0, 1.1, 0]}
        scale={[0.28, 0.14, 0.28]}
      />
      <mesh
        geometry={nodes.Icosphere003.geometry}
        material={materials["Material.004"]}
        position={[-5.31, -0.33, -2.63]}
        rotation={[0.85, 0.98, Math.PI]}
        scale={[0.33, 0.43, 0.33]}
      />
      <mesh
        geometry={nodes.Sphere_Sphere001.geometry}
        material={materials["Material.004"]}
        position={[-4.65, -0.18, -2.91]}
        rotation={[1.07, -0.66, -2.3]}
        scale={[1.76, 1.17, 1.21]}
      />
      <mesh
        geometry={nodes.Sphere_Sphere003.geometry}
        material={materials["Material.004"]}
        position={[-4.73, -0.37, -2.46]}
        rotation={[1.12, 0.85, 0]}
        scale={[1.36, 1.46, 1.48]}
      />
      <mesh
        geometry={nodes.Sphere001_Sphere.geometry}
        material={materials["Material.004"]}
        position={[-4.38, -0.22, -1.68]}
        rotation={[-1.5, 0, 0]}
        scale={1.34}
      />
      <mesh
        geometry={nodes.Icosphere005.geometry}
        material={materials["Material.004"]}
        position={[-3.93, -0.17, -1.14]}
        rotation={[-1.38, 0, 0]}
        scale={1.26}
      />
      <mesh
        geometry={nodes.Icosphere001.geometry}
        material={materials["Material.004"]}
        position={[-4.41, -0.12, -1.16]}
        scale={[0.24, 0.16, 0.24]}
      />
      <mesh
        geometry={nodes.Sphere_Sphere002.geometry}
        material={materials["Material.004"]}
        position={[-3.03, -0.42, -0.53]}
        rotation={[1.12, 0.85, 0]}
        scale={[1.36, 1.46, 1.48]}
      />
      <mesh
        geometry={nodes.Sphere001_Sphere001.geometry}
        material={materials["Material.004"]}
        position={[-2.31, -0.35, -0.4]}
        rotation={[-1.51, 0.02, 0.33]}
        scale={1.17}
      />
      <mesh
        geometry={nodes.Sphere001_Sphere002.geometry}
        material={materials["Material.004"]}
        position={[-1.8, -0.53, -0.4]}
        rotation={[-1.51, 0.02, 0.33]}
        scale={[0.78, 1.14, 3.12]}
      />
      <mesh
        geometry={nodes.Sphere_Sphere004.geometry}
        material={materials["Material.004"]}
        position={[3.04, -0.42, -3.7]}
        rotation={[1.12, 0.85, 0]}
        scale={[1.36, 1.46, 1.48]}
      />
      <mesh
        geometry={nodes.Sphere001_Sphere003.geometry}
        material={materials["Material.004"]}
        position={[3.76, -0.16, -3.56]}
        rotation={[-1.51, 0.02, 0.33]}
        scale={[1.17, 1.17, 1.53]}
      />
      <mesh
        geometry={nodes.Sphere001_Sphere004.geometry}
        material={materials["Material.004"]}
        position={[4.27, -0.53, -3.56]}
        rotation={[-1.51, 0.02, 0.33]}
        scale={[0.78, 1.14, 3.12]}
      />
      <mesh
        geometry={nodes.Sphere_Sphere005.geometry}
        material={materials["Material.004"]}
        position={[3.13, -0.65, -2.61]}
        rotation={[1.12, 0.85, 0]}
        scale={[1.36, 1.46, 1.48]}
      />
      <mesh
        geometry={nodes.Icosphere004.geometry}
        material={materials["Material.004"]}
        position={[2.84, -0.29, -1.95]}
        rotation={[-1.39, -0.04, -0.24]}
        scale={[1.26, 1.3, 1.21]}
      />
      <mesh
        geometry={nodes.Icosphere006.geometry}
        material={materials["Material.004"]}
        position={[3.61, -0.24, -2.95]}
        rotation={[-Math.PI, 1.37, -Math.PI]}
        scale={[0.5, 0.34, 0.5]}
      />
      <mesh
        geometry={nodes.Plane029.geometry}
        material={materials["tiles-stone.001"]}
        position={[0, -0.67, 0]}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials.Water}
        position={[0, 0.01, 0]}
        scale={[0.99, 0.9, 0.99]}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.Woodtile}
        position={[0.01, 1.65, -1.15]}
      />
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials.Flag}
        position={[0.01, 6.16, -3.09]}
      />
      <group
        position={[1.52, 0.22, 0.83]}
        rotation={[0.38, 0, 0]}
        scale={[1, 0.11, 0.7]}
      >
        <mesh geometry={nodes.Plane032.geometry} material={materials.deck} />
        <mesh geometry={nodes.Plane032_1.geometry} material={materials.roof} />
      </group>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials.roof}
        position={[1.67, -0.2, 3.24]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials.roof}
        position={[1.02, -0.2, 3.24]}
        rotation={[Math.PI, -0.16, Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials.roof}
        position={[1.67, -0.21, 1.1]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials.roof}
        position={[1.02, -0.19, 2.16]}
        rotation={[-Math.PI, 0.01, -Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials.roof}
        position={[1.02, -0.15, 1.1]}
        rotation={[0, 0.91, 0]}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={materials.roof}
        position={[1.67, -0.15, 2.17]}
        rotation={[Math.PI, -0.9, Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={materials.roof}
        position={[1.76, 0.09, 0.34]}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={materials.roof}
        position={[1.76, 0.06, -0.38]}
      />
      <mesh
        geometry={nodes.Cylinder008.geometry}
        material={materials.roof}
        position={[-0.88, 0.1, 0.34]}
        rotation={[Math.PI, -1.02, Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder009.geometry}
        material={materials.roof}
        position={[-0.88, 0.05, -0.38]}
        rotation={[0, 1.52, 0]}
      />
      <mesh
        geometry={nodes.Cylinder010.geometry}
        material={materials.roof}
        position={[0.54, 0.06, 0.34]}
        rotation={[0, -1.07, 0]}
      />
      <mesh
        geometry={nodes.Cylinder011.geometry}
        material={materials.roof}
        position={[0.54, 0.08, -0.38]}
        rotation={[Math.PI, -1.26, Math.PI]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials.tower}
        position={[1.35, 0.48, 3.23]}
      />
      <mesh
        geometry={nodes.Text.geometry}
        material={materials.Flag}
        position={[1.09, 0.4, 3.32]}
        rotation={[Math.PI / 2, 0.23, 0]}
      />
      <mesh
        geometry={nodes.Text001.geometry}
        material={materials.Flag}
        position={[1.56, 0.41, 3.32]}
        rotation={[Math.PI / 2, -0.21, 0]}
      />
      <mesh
        geometry={nodes.Text002.geometry}
        material={materials["tower-top"]}
        position={[1.33, 0.44, 3.32]}
        rotation={[Math.PI / 2, 0.01, 0]}
      />
      <SeaPlane
        nodes={nodes}
        materials={materials}
        planeColor={props.planeColor}
      />
    </group>
  );
}

useGLTF.preload("./models/seaPlane.glb");
